server {
    listen 80;

    location = / {
        return 301 /diffusion_techniques/;
    }

    location /diffusion_techniques/ {
        alias /usr/share/nginx/html/diffusion_techniques/;
        index index.html;
        try_files $uri $uri/ /diffusion_techniques/index.html;
    }

    # Backup in case of wrong requests
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /diffusion_techniques/index.html;
    }

    error_page 404 /diffusion_techniques/index.html;
}
